# Generated by Django 5.0.7 on 2024-08-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.invoice'),
        ),
    ]
