# Generated by Django 5.1.6 on 2025-02-20 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("customers", "0004_customer_is_active"),
        ("orders", "0004_orderskuview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name="billingreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="billingreport",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reports",
                to='auth.user',
            ),
        ),
        migrations.AddField(
            model_name="billingreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="billingreport",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_reports",
                to='auth.user',
            ),
        ),
        migrations.AddIndex(
            model_name="billingreport",
            index=models.Index(
                fields=["customer", "start_date", "end_date"],
                name="billing_bil_custome_a865ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingreport",
            index=models.Index(
                fields=["generated_at"], name="billing_bil_generat_93d22c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingreport",
            index=models.Index(
                fields=["created_at"], name="billing_bil_created_cc710c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingreportdetail",
            index=models.Index(
                fields=["report", "order"], name="billing_bil_report__69e5c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingreportdetail",
            index=models.Index(
                fields=["total_amount"], name="billing_bil_total_a_eb75da_idx"
            ),
        ),
    ]
