# Generated by Django 5.1.6 on 2025-02-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_billingreport_created_at_billingreport_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="billingreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
