# Generated by Django 5.0.7 on 2024-08-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingrule',
            old_name='item_count_operator',
            new_name='operator1',
        ),
        migrations.RenameField(
            model_name='billingrule',
            old_name='order_total_operator',
            new_name='operator2',
        ),
        migrations.RemoveField(
            model_name='billingrule',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='billingrule',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='billingrule',
            name='excluded_skus',
        ),
        migrations.RemoveField(
            model_name='billingrule',
            name='included_skus',
        ),
        migrations.RemoveField(
            model_name='billingrule',
            name='item_count_threshold',
        ),
        migrations.RemoveField(
            model_name='billingrule',
            name='order_total_threshold',
        ),
        migrations.AddField(
            model_name='billingrule',
            name='logical_operator',
            field=models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='pick_column',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='pick_column2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='value1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='value2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BillingCriteria',
        ),
    ]
