version: '3.8'

services:
  # PostgreSQL database for testing
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ledgerlink_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  # Test runner service
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python -m pytest"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=LedgerLink.settings.test
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ledgerlink_test

volumes:
  postgres_test_data: