# Generated by Django 5.0.6 on 2024-06-06 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('legal_business_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('labeling_unit_1', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_1', models.PositiveIntegerField(blank=True, null=True)),
                ('labeling_unit_2', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_2', models.PositiveIntegerField(blank=True, null=True)),
                ('labeling_unit_3', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_3', models.PositiveIntegerField(blank=True, null=True)),
                ('labeling_unit_4', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_4', models.PositiveIntegerField(blank=True, null=True)),
                ('labeling_unit_5', models.CharField(blank=True, max_length=50, null=True)),
                ('labeling_quantity_5', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('customer_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.service')),
            ],
        ),
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('insert_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100)),
                ('insert_name', models.CharField(max_length=100)),
                ('insert_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['sku', 'customer'], name='idx_ins_sku_cust_id')],
            },
        ),
        migrations.AddConstraint(
            model_name='insert',
            constraint=models.CheckConstraint(check=models.Q(('insert_quantity__gte', 0)), name='insert_quantity_check'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['customer'], name='idx_prod_cust_id'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_1__gte', 0)), name='products_label_qty_1_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_2__gte', 0)), name='products_label_qty_2_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_3__gte', 0)), name='products_label_qty_3_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_4__gte', 0)), name='products_label_qty_4_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_5__gte', 0)), name='products_label_qty_5_check'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'customer')},
        ),
        migrations.AddIndex(
            model_name='customerservice',
            index=models.Index(fields=['customer'], name='idx_cust_svc_cust_id'),
        ),
        migrations.AddIndex(
            model_name='customerservice',
            index=models.Index(fields=['service'], name='idx_cust_svc_svc_id'),
        ),
        migrations.AlterUniqueTogether(
            name='customerservice',
            unique_together={('customer', 'service')},
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['customer'], name='idx_svc_logs_cust_id'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['service'], name='idx_svc_logs_svc_id'),
        ),
        migrations.AddIndex(
            model_name='servicelog',
            index=models.Index(fields=['sku', 'customer'], name='idx_svc_logs_sku_cust_id'),
        ),
        migrations.AddConstraint(
            model_name='servicelog',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='svc_logs_qty_check'),
        ),
    ]
