# Generated by Django 5.0.6 on 2024-06-06 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=100)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=50)),
                ('ship_to_name', models.CharField(max_length=100)),
                ('ship_to_company', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_address', models.CharField(max_length=200)),
                ('ship_to_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('ship_to_city', models.CharField(max_length=100)),
                ('ship_to_state', models.CharField(max_length=50)),
                ('ship_to_zip', models.CharField(max_length=20)),
                ('ship_to_country', models.CharField(max_length=50)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('total_weight_lb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_items', models.IntegerField()),
                ('sku_quantity', models.JSONField()),
                ('total_item_qty', models.IntegerField()),
                ('volume_cuft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('packages', models.IntegerField()),
                ('markfor_lists', models.TextField(blank=True, null=True)),
                ('ship_service', models.CharField(blank=True, max_length=100, null=True)),
                ('warehouse_instructions', models.TextField(blank=True, null=True)),
                ('allocation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('asn_sent_date', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_of_lading', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('confirm_asn_sent_date', models.DateTimeField(blank=True, null=True)),
                ('earliest_ship_date', models.DateTimeField(blank=True, null=True)),
                ('end_of_day_request_date', models.DateTimeField(blank=True, null=True)),
                ('load_number', models.CharField(blank=True, max_length=50, null=True)),
                ('load_out_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('load_out_date', models.DateTimeField(blank=True, null=True)),
                ('markfor_name_id', models.CharField(blank=True, max_length=100, null=True)),
                ('master_bill_of_lading', models.CharField(blank=True, max_length=100, null=True)),
                ('pack_done_date', models.DateTimeField(blank=True, null=True)),
                ('parcel_label_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pick_done_date', models.DateTimeField(blank=True, null=True)),
                ('pick_job_assignee', models.CharField(blank=True, max_length=50, null=True)),
                ('pick_job_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pick_ticket_print_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=100, null=True)),
                ('retailer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_to_email', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_to_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('small_parcel_ship_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('create_source', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['create_date'], name='idx_orders_create_date'), models.Index(fields=['customer'], name='idx_orders_customer_id'), models.Index(fields=['reference_number'], name='idx_orders_reference_number'), models.Index(fields=['status'], name='idx_orders_status'), models.Index(fields=['tracking_number'], name='idx_orders_tracking_number'), models.Index(fields=['transaction_id'], name='idx_orders_transaction_id')],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('line_items__gte', 0)), name='orders_line_items_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('load_out_percent__gte', 0), ('load_out_percent__lte', 100)), name='orders_load_out_percent_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('packages__gte', 0)), name='orders_packages_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_item_qty__gte', 0)), name='orders_total_item_qty_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_weight_kg__gte', 0)), name='orders_total_weight_kg_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_weight_lb__gte', 0)), name='orders_total_weight_lb_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('volume_cuft__gte', 0)), name='orders_volume_cuft_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('volume_m3__gte', 0)), name='orders_volume_m3_check'),
        ),
    ]
