# Generated by Django 5.0.6 on 2024-06-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_order_orders_line_items_check_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
