# Generated by Django 5.0.6 on 2024-06-09 02:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('box_id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('prices', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BoxPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='insert',
            name='insert_quantity_check',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_label_qty_1_check',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_label_qty_2_check',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_label_qty_3_check',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_label_qty_4_check',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='products_label_qty_5_check',
        ),
        migrations.RemoveConstraint(
            model_name='servicelog',
            name='svc_logs_qty_check',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='idx_orders_customer_id',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_prod_cust_id',
        ),
        migrations.RemoveIndex(
            model_name='servicelog',
            name='idx_svc_logs_cust_id',
        ),
        migrations.RemoveIndex(
            model_name='servicelog',
            name='idx_svc_logs_svc_id',
        ),
        migrations.RemoveIndex(
            model_name='servicelog',
            name='idx_svc_logs_sku_cust_id',
        ),
        migrations.RenameIndex(
            model_name='customerservice',
            new_name='cust_serv_cust_id_idx',
            old_name='idx_cust_svc_cust_id',
        ),
        migrations.RenameIndex(
            model_name='customerservice',
            new_name='cust_serv_serv_id_idx',
            old_name='idx_cust_svc_svc_id',
        ),
        migrations.RenameIndex(
            model_name='insert',
            new_name='ins_sku_cust_idx',
            old_name='idx_ins_sku_cust_id',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_create_date_idx',
            old_name='idx_orders_create_date',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_ref_num_idx',
            old_name='idx_orders_reference_number',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_status_idx',
            old_name='idx_orders_status',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_track_num_idx',
            old_name='idx_orders_tracking_number',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_trans_id_idx',
            old_name='idx_orders_transaction_id',
        ),
        migrations.AlterUniqueTogether(
            name='customerservice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='insert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='insert',
            name='insert_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='labeling_quantity_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='labeling_quantity_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='labeling_quantity_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='labeling_quantity_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='labeling_quantity_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='performed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('email',)},
        ),
        migrations.AddIndex(
            model_name='insert',
            index=models.Index(fields=['customer'], name='ins_cust_id_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_id'], name='order_cust_id_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_id'], name='orders_customer_id_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['customer_id'], name='product_cust_id_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_name'], name='billing_svc_name_idx', opclasses=['varchar_pattern_ops']),
        ),
        migrations.AddConstraint(
            model_name='customerservice',
            constraint=models.UniqueConstraint(fields=('customer', 'service'), name='customer_service_cust_serv_key'),
        ),
        migrations.AddConstraint(
            model_name='insert',
            constraint=models.CheckConstraint(check=models.Q(('insert_quantity__gte', 0)), name='insert_qty_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku', 'customer_id'), name='billing_product_sku_customer_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_1__gte', 0)), name='billing_product_labeling_quantity_1_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_2__gte', 0)), name='billing_product_labeling_quantity_2_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_3__gte', 0)), name='billing_product_labeling_quantity_3_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_4__gte', 0)), name='billing_product_labeling_quantity_4_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_5__gte', 0)), name='billing_product_labeling_quantity_5_check'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('service_name',), name='billing_service_service_name_key'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('service_name',), name='unique_service_name_key'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['length', 'width', 'height'], name='billing_box_length_62d69d_idx'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.CheckConstraint(check=models.Q(('length__gt', 0)), name='length_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.CheckConstraint(check=models.Q(('width__gt', 0)), name='width_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.CheckConstraint(check=models.Q(('height__gt', 0)), name='height_gt_0'),
        ),
        migrations.AddField(
            model_name='boxprice',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_prices', to='billing.box'),
        ),
        migrations.AddIndex(
            model_name='boxprice',
            index=models.Index(fields=['box', 'test_type'], name='billing_box_box_id_1a4694_idx'),
        ),
        migrations.AddConstraint(
            model_name='boxprice',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_gte_0'),
        ),
        migrations.AlterUniqueTogether(
            name='boxprice',
            unique_together={('box', 'test_type')},
        ),
    ]
