# Generated by Django 5.0.6 on 2024-06-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_box_boxprice_material_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='service',
            name='unique_service_name_key',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
