# Generated by Django 5.0.6 on 2024-06-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_customerservice_customer_service_cust_serv_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerservice',
            name='cust_svc_key',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ord_line_items_chk',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ord_load_out_perc_chk',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ord_packages_chk',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ord_tot_item_qty_chk',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ord_tot_weight_kg_chk',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ord_tot_weight_lb_chk',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ord_vol_cuft_chk',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='ord_vol_m3_chk',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='prod_sku_cust_id_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='prod_label_qty1_chk',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='prod_label_qty2_chk',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='prod_label_qty3_chk',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='prod_label_qty4_chk',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='prod_label_qty5_chk',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='svc_name_key',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='prod_cust_id_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='billing_customer_email_idx',
            old_name='cust_email_idx',
        ),
        migrations.RenameIndex(
            model_name='customerservice',
            new_name='cust_serv_cust_id_idx',
            old_name='cust_svc_cust_id_idx',
        ),
        migrations.RenameIndex(
            model_name='customerservice',
            new_name='cust_serv_serv_id_idx',
            old_name='cust_svc_svc_id_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_cust_id_idx',
            old_name='ord_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_create_date_idx',
            old_name='ord_create_date_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_ref_num_idx',
            old_name='ord_ref_num_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_status_idx',
            old_name='ord_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_track_num_idx',
            old_name='ord_track_num_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_trans_id_idx',
            old_name='ord_trans_id_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='billing_svc_name_idx',
            old_name='svc_name_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['customer'], name='product_cust_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerservice',
            constraint=models.UniqueConstraint(fields=('customer', 'service'), name='customer_service_cust_serv_key'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('line_items__gte', 0)), name='orders_line_items_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('load_out_percent__gte', 0), ('load_out_percent__lte', 100)), name='orders_load_out_percent_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('packages__gte', 0)), name='orders_packages_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_item_qty__gte', 0)), name='orders_total_item_qty_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_weight_kg__gte', 0)), name='orders_total_weight_kg_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_weight_lb__gte', 0)), name='orders_total_weight_lb_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('volume_cuft__gte', 0)), name='orders_volume_cuft_check'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('volume_m3__gte', 0)), name='orders_volume_m3_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('sku', 'customer'), name='billing_product_sku_customer_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_1__gte', 0)), name='billing_product_labeling_quantity_1_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_2__gte', 0)), name='billing_product_labeling_quantity_2_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_3__gte', 0)), name='billing_product_labeling_quantity_3_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_4__gte', 0)), name='billing_product_labeling_quantity_4_check'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('labeling_quantity_5__gte', 0)), name='billing_product_labeling_quantity_5_check'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('service_name',), name='billing_service_service_name_key'),
        ),
    ]
