# Generated by Django 5.1.6 on 2025-03-11 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0004_customer_is_active"),
        ("orders", "0005_create_sku_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("service_totals", models.JSONField(default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_reports_v2",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing Report",
                "verbose_name_plural": "Billing Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "billing_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_costs",
                        to="Billing_V2.billingreport",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_costs_v2",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Cost",
                "verbose_name_plural": "Order Costs",
            },
        ),
        migrations.CreateModel(
            name="ServiceCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.IntegerField()),
                ("service_name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_costs",
                        to="Billing_V2.ordercost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Cost",
                "verbose_name_plural": "Service Costs",
            },
        ),
    ]
