# Generated by Django 3.2.25 on 2025-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing_V2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingreport',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for the report (customer service selection, etc.)'),
        ),
    ]
