import { Verifier } from '@pact-foundation/pact';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the directory of the current module
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Verifies that the provider (Django backend) adheres to the Pact contract
 * generated by the consumer (React frontend) tests.
 *
 * This script is used in CI/CD to ensure both sides of the API contract
 * remain synchronized.
 */
const verifyPact = async () => {
  // Provider base URL
  const providerBaseUrl = process.env.PROVIDER_BASE_URL || 'http://localhost:8000';
  
  // Path to pacts directory containing the contract files
  const pactsDir = path.resolve(__dirname, '../pacts');
  
  const options = {
    provider: 'LedgerLinkAPI',
    providerBaseUrl: providerBaseUrl,
    pactUrls: [
      path.resolve(pactsDir, 'LedgerLinkFrontend-LedgerLinkAPI.json'),
    ],
    publishVerificationResult: process.env.CI === 'true',
    providerVersion: process.env.PROVIDER_VERSION || '1.0.0',
    providerVersionTags: process.env.PROVIDER_TAGS ? process.env.PROVIDER_TAGS.split(',') : ['dev'],
    // Provider state support
    providerStatesSetupUrl: `${providerBaseUrl}/api/v1/pact/provider-states`,
    logLevel: 'info',
  };

  try {
    const output = await new Verifier(options).verifyProvider();
    console.log('Pact verification completed successfully');
    console.log(output);
    process.exit(0);
  } catch (error) {
    console.error('Pact verification failed', error);
    process.exit(1);
  }
};

verifyPact();