# Generated by Django 5.0.7 on 2024-08-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('customers', '0003_alter_customer_id'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total_operator', models.CharField(blank=True, choices=[('>', 'greater than'), ('<', 'less than'), ('==', 'equal to'), ('>=', 'greater than or equal to'), ('<=', 'less than or equal to')], max_length=2, null=True)),
                ('order_total_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_count_operator', models.CharField(blank=True, choices=[('>', 'greater than'), ('<', 'less than'), ('==', 'equal to'), ('>=', 'greater than or equal to'), ('<=', 'less than or equal to')], max_length=2, null=True)),
                ('item_count_threshold', models.IntegerField(blank=True, null=True)),
                ('included_skus', models.TextField(blank=True, null=True)),
                ('excluded_skus', models.TextField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
