# Generated by Django 5.1.3 on 2024-11-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_rulegroup_rule_delete_billingcriteria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingCriteria',
        ),
    ]
