# Generated by Django 5.0.7 on 2024-08-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_rulegroup_rule_delete_billingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='adjustment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to adjust the price', max_digits=10, null=True),
        ),
    ]
