# Generated by Django 5.1 on 2024-08-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_rule_adjustment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.CharField(help_text='For multiple values, separate them with a semicolon (;)', max_length=255),
        ),
    ]
