# Generated by Django 5.1.5 on 2025-02-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0002_add_tier_config"),
        ("rules", "0008_alter_rule_field"),
    ]

    operations = []
