# Generated by Django 5.1.6 on 2025-02-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_services", "0006_create_missing_tables_and_views"),
        ("rules", "0011_add_cascade_delete_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="adjustment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount to adjust the price when this rule applies",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="field",
            field=models.CharField(
                choices=[
                    ("reference_number", "Reference Number"),
                    ("ship_to_name", "Ship To Name"),
                    ("ship_to_company", "Ship To Company"),
                    ("ship_to_city", "Ship To City"),
                    ("ship_to_state", "Ship To State"),
                    ("ship_to_country", "Ship To Country"),
                    ("sku_count", "SKU Count"),
                    ("sku_name", "SKU Name"),
                    ("sku_quantity", "SKU Quantity"),
                    ("total_item_qty", "Total Item Quantity"),
                    ("packages", "Packages"),
                    ("notes", "Notes"),
                    ("carrier", "Carrier"),
                    ("volume_cuft", "Volume (cuft)"),
                    ("weight_lb", "Weight (lb)"),
                    ("line_items", "Line Items"),
                ],
                db_index=True,
                help_text="Order field to evaluate",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="operator",
            field=models.CharField(
                choices=[
                    ("gt", "Greater than"),
                    ("lt", "Less than"),
                    ("eq", "Equals"),
                    ("ne", "Not equals"),
                    ("ge", "Greater than or equals"),
                    ("le", "Less than or equals"),
                    ("in", "In"),
                    ("ni", "Not in"),
                    ("contains", "Contains"),
                    ("ncontains", "Not contains"),
                    ("only_contains", "Only Contains"),
                    ("startswith", "Starts with"),
                    ("endswith", "Ends with"),
                ],
                help_text="Comparison operator",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="rule_group",
            field=models.ForeignKey(
                help_text="The rule group this rule belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="rules.rulegroup",
            ),
        ),
        migrations.AlterField(
            model_name="rulegroup",
            name="customer_service",
            field=models.ForeignKey(
                help_text="The customer service this rule group applies to",
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_services.customerservice",
            ),
        ),
        migrations.AlterField(
            model_name="rulegroup",
            name="logic_operator",
            field=models.CharField(
                choices=[
                    ("AND", "All conditions must be true (AND)"),
                    ("OR", "Any condition can be true (OR)"),
                    ("NOT", "Condition must not be true (NOT)"),
                    ("XOR", "Only one condition must be true (XOR)"),
                    ("NAND", "At least one condition must be false (NAND)"),
                    ("NOR", "None of the conditions must be true (NOR)"),
                ],
                default="AND",
                help_text="Logic operator to apply when evaluating rules in this group",
                max_length=5,
            ),
        ),
    ]
