# Generated by Django 5.1.5 on 2025-02-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_add_order_search_indexes"),
        ("orders", "0002_create_materialized_sku_view"),
        ("orders", "0002_order_priority_order_status"),
    ]

    operations = []
