# Generated by Django 5.1.6 on 2025-02-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_merge_20250218_1625"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSKUView",
            fields=[
                (
                    "transaction_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("close_date", models.DateTimeField(blank=True, null=True)),
                ("reference_number", models.CharField(max_length=100)),
                (
                    "ship_to_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ship_to_company",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ship_to_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ship_to_address2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ship_to_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ship_to_state",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ship_to_zip", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "ship_to_country",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "weight_lb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("line_items", models.IntegerField(blank=True, null=True)),
                ("total_item_qty", models.IntegerField(blank=True, null=True)),
                (
                    "volume_cuft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("packages", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("carrier", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(max_length=20)),
                ("priority", models.CharField(max_length=20)),
                ("sku_name", models.CharField(max_length=100)),
                ("sku_count", models.IntegerField()),
                ("cases", models.IntegerField()),
                ("picks", models.IntegerField()),
                ("case_size", models.IntegerField(null=True)),
                ("case_unit", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "orders_sku_view",
                "managed": False,
            },
        ),
    ]
